/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.nanosite.xwarp_client;

import java.util.Map;

import org.nanosite.xwarp.model.IBehavior;
import org.nanosite.xwarp.model.IConsumer;
import org.nanosite.xwarp.model.IModel;
import org.nanosite.xwarp.model.IProcessor;
import org.nanosite.xwarp.model.IStep;
import org.nanosite.xwarp.model.ModelBuilder;
import org.nanosite.xwarp.simulation.WLogger;
import org.nanosite.xwarp.simulation.WSimulator;
import org.nanosite.xwarp.result.ISimResult;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        ModelBuilder builder = new ModelBuilder(ModelBuilder.Unit.MILLISECONDS);
        IModel model = builder.model();
        IProcessor proc = builder.processor("Proc1");
        builder.add(model, proc);

        IConsumer comp1 = builder.consumer("Comp1");
        builder.add(model, comp1);

        IBehavior bhvr = builder.behavior("Behavior1");
        builder.add(comp1, bhvr);

        IStep s1 = builder.step("Step1", 0L, Map.of(proc, 10L));
        builder.add(bhvr, s1);
        IStep s2 = builder.step("Step2", 0L, Map.of(proc, 50L));
        builder.add(bhvr, s2);
        IStep s3 = builder.step("Step3", 0L, Map.of(proc, 40L));
        builder.add(bhvr, s3);

        builder.addInitial(model, bhvr);

        WSimulator sim = new WSimulator(new WLogger(2));
        ISimResult result = sim.simulate(model);
        result.dump();
    }
}
