/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.nanosite.xwarp_client;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void simulationIsRunning() {
        App classUnderTest = new App();
        int nIterations = classUnderTest.runSimulation();
        assertEquals(3, nIterations);
    }
}
